---

# Applies hardening to the PCE nodes to protect PCE related services

- name: "Install IPTables if required"
  yum:
    state: latest
    name: ["iptables","iptables-services"]
  when: "prefix_name in group_names"


- name: "Prevent firewalld from getting loaded"
  systemd:
    name: firewalld
    state: stopped
    enabled: no
    masked: yes
  when: "prefix_name in group_names"


- name: "Enable iptables"
  systemd:
    name: iptables
    state: started
    enabled: yes
  when: "prefix_name in group_names"


- name: "Create the working directory"
  file:
    path: /var/tmp/illumio-pipgen
    state: directory
  when: "prefix_name in group_names"


- name: "Copy illumio-pipgen to the PCE nodes"
  copy:
    src: ilo-pipgen
    dest: /var/tmp/illumio-pipgen/
    mode: 0755
  when: "prefix_name in group_names"


- name: "Create pipgen IP file"
  template: 
    src: ip_addr_input.txt
    dest: /var/tmp/illumio-pipgen/
  when: "prefix_name in group_names"


- name: "Run pipgen"
  shell: "./ilo-pipgen -i ip_addr_input.txt -o iptables -p {{ven_port}},{{ven_lightning_port}},{{mgmt_port}}"
  args:
    chdir: /var/tmp/illumio-pipgen/
  when: "prefix_name in group_names"


- name: "Enable conntrack in modprobe"
  modprobe:
    name: nf_conntrack
    state: present
  when: "prefix_name in group_names"


- name: "Update nf_conntrack_max value"
  shell: echo 1048576 > /proc/sys/net/nf_conntrack_max
  when: "prefix_name in group_names"


- name: "Update nf_conntrack_hashsize value"
  shell: echo 262144 > /sys/module/nf_conntrack/parameters/hashsize
  when: "prefix_name in group_names"


- name: "Update nf_conntrack_max boot value"
  shell: echo "net.nf_conntrack_max=1048576" > /etc/sysctl.d/illumio.con
  when: "prefix_name in group_names"


- name: "Update nf_conntrack_hashsize boot value"
  shell: echo "options nf_conntrack hashsize=262144" > /etc/modprobe.d/illumio.conf
  when: "prefix_name in group_names"


- name: "Check for existing IPTables Config"
  stat: 
    path: /etc/sysconfig/iptables
  register: ipt_stat
  when: "prefix_name in group_names"


- name: "Check for initial IPTables pipgen backup"
  stat:
    path: /etc/sysconfig/iptables.pipgen.orig
  register: ipt_pipgen_stat
  when: "prefix_name in group_names"


- name: "Backup original IPTables Config"
  command: mv /etc/sysconfig/iptables /etc/sysconfig/iptables.pipgen.orig
  when: "prefix_name in group_names and ipt_stat.stat.exists and ipt_pipgen_stat.stat.exists == false"


- name: "Insert pipgen firewall"
  command: cp /var/tmp/illumio-pipgen/iptables /etc/sysconfig/iptables
  when: "prefix_name in group_names"


- name: "Clean up pipgen temp directory"
  file:
    path: /var/tmp/illumio-pipgen/
    state: absent
  when: "prefix_name in group_names" 


- name: "Restart IP Tables and apply pipgen firewall"
  systemd:
    name: iptables
    state: restarted
  when: "prefix_name in group_names"


# - name: "Dependancy check for ilo-vpngen"
#   yum:
#     state: present
#     name: ["ldns","libevent","libpcap","nss-softokn","nss-softokn-freebl","nss-sysinit","nss-util"]
#   when: "prefix_name in group_names"


# - name: "Dependancy check updates for ilo-vpngen"
#   yum:
#     state: latest
#     name: ["nss","nspr","nss-tools","unbound-libs"]
#   when: "prefix_name in group_names"

# - name: "Copy libreswan 3.29-1 to PCE"
#   copy:
#       src: "libreswan-3.29-1.el7.x86_64.rpm"
#       dest: /tmp/
#   when: "prefix_name in group_names"


# - name: "Install libreswan v3.29-1"
#   yum:
#     state: present
#     name: /tmp/libreswan-3.29-1.el7.x86_64.rpm
#   when: "prefix_name in group_names"
# - name: "Clean up RPM package"
#   file:
#       path: /tmp/libreswan-3.29-1.el7.x86_64.rpm
#       state: absent
#   when: "prefix_name in group_names"


# - name: "Create the vpngen working directory"
#   file:
#     path: /var/tmp/illumio-vpngen
#     state: directory
#   when: "prefix_name in group_names and node_type in ['core0']"


# - name: "Copy illumio-vpngen to the PCE nodes"
#   copy:
#     src: ilo-vpngen
#     dest: /var/tmp/illumio-vpngen/
#     mode: 0755
#   when: "node_type in ['core0'] and prefix_name in group_names"

# - name: "Create vpngen IP file"
#   template:
#     src: ip_addr_input.txt
#     dest: /var/tmp/illumio-vpngen/
#   when: "node_type in ['core0'] and prefix_name in group_names"


# - name: "Run vpngen"
#   shell: "./ilo-vpngen -i ip_addr_input.txt -o deploy_vpn.sh"
#   args:
#     chdir: /var/tmp/illumio-vpngen/
#   when: "node_type in ['core0'] and prefix_name in group_names"


# - name: "Collect generate VPN Config"
#   fetch: 
#     src: /var/tmp/illumio-vpngen/deploy_vpn.sh 
#     dest: /tmp/
#     flat: yes
#   when: "node_type in ['core0'] and prefix_name in group_names"


# - name: "Clean up pipgen temp directory"
#   file:
#     path: /var/tmp/illumio-vpngen/
#     state: absent
#   when: "node_type in ['core0'] and prefix_name in group_names"

# - name: "Distribute config to PCE nodes"
#   copy: 
#     src: /tmp/deploy_vpn.sh 
#     dest: /tmp/deploy_vpn.sh
#     mode: 0755
#   when: "prefix_name in group_names"


# - name: "Configure illumio vpngen"
#   command: /tmp/deploy_vpn.sh
#   when: "prefix_name in group_names"


# - name: "Restart the IPSec daemon"
#   systemd:
#     name: ipsec
#     state: restarted
#   when: "prefix_name in group_names"


# - name: "Clean up pipgen temp directory"
#   file:
#     path: /tmp/illumio-vpngen/
#     state: absent
#   when: "prefix_name in group_names"
